<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Box-O-Rama</title>
    <id>magicbox.empty</id>
    <author>Tal Erez</author>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
  </info>
  <variables>
    <variable id="null" name="boxes" type="list" value="{75,75,4,1,0},{1360,365,2,1,0},{825,180.25000000000006,5,1,0},{75,450.5,2,1,1},{449.99999999999994,300.50000000000006,4,1,0}" min="0" max="0" title="Test List" showSettings="false" description="null"/>
    <variable id="null" name="outline" type="list" value="{1555,962},{1480,962},{1480,740},{1285,740},{1285,555.25},{825,555.25},{825,675.5},{825,962},{750,962},{750,675.5},{374.99999999999994,675.5},{374.99999999999994,645.5},{75,645.5},{75,962},{0,962},{0,645.5},{0,375.5},{0,0},{449.99999999999994,0},{449.99999999999994,225.50000000000006},{750,225.50000000000006},{750,105.25000000000006},{1360,105.25000000000006},{1360,290},{1555,290},{1555,740},{1555,962}" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="legs" type="list" value="{37.5,316.50000000000006},{1517.5,222.00000000000003},{787.5,286.50000000000006}" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="holes" type="list" value="" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="depth" type="slider" value="438" min="0" max="700" title="null" showSettings="false" description="null"/>
    <variable id="null" name="thickness" type="slider" value="12.042253521126762" min="0" max="30" title="null" showSettings="false" description="null"/>
    <variable id="null" name="pf" type="slider" value="45" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="height" type="slider" value="957.8313253012047" min="0" max="1500" title="null" showSettings="false" description="null"/>
    <variable id="null" name="leghole" type="slider" value="37.5" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="bottomdistance" type="slider" value="25.833333333333336" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="legthickness" type="slider" value="24.583333333333332" min="0" max="100" title="null" showSettings="false" description="null"/>
    <variable id="null" name="width" type="slider" value="1443.661971830986" min="0" max="5000" title="null" showSettings="true" description="null"/>
  </variables>
  <layers>null</layers>
</parametricbox>