<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Magic Box Design</title>
    <id>magicbox.empty</id>
    <author/>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
  </info>
  <variables>
    <variable name="width" title="Width" min="10" max="700" value="106.91011235955057" type="slider"/>
    <variable name="height" title="Height" min="10" max="700" value="50" type="slider"/>
    <variable name="thickness" title="Thickness" min="0" max="6" value="2" type="slider"/>
    <variable name="testlist" title="Test List" value="1,2,3,4,5" type="list"/>
  </variables>
  <layers>
    <rect stroke="#DDDDDD" stroke-width="1" stroke-opacity="1" fill="#888888" fill-opacity="0.5" visibility="visible" width="100" height="100" mb_x="0" mb_y="0" mb_width="width" mb_height="height" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="false" mb__showTransform="false" id="rect 1">
      <transforms/>
    </rect>
    <text mb_x="width/2" mb_y="height/2" mb_fill="#888888" mb_opacity="1" mb_visibility="visible" mb_fontSize="6" mb_fontFamily="Arial" mb_textAnchor="middle" mb__showFill="true" mb__showStroke="false" mb__showTransform="false" mb__text="This is text that is centered &#xD;and a bit more to allow &#xD;for any changes to be made" id="text 0">
      <transforms/>
    </text>
  </layers>
</parametricbox>