<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Magic Box Design</title>
    <id>magicbox.empty</id>
    <author></author>
    <website></website>
    <tutorial></tutorial>
    <description>A default design</description>
  </info>
  <variables>
    <variable name="m" title="Width" min="0" max="15" value="8" type="stepper" showSettings="true"/>
    <variable name="n1" title="Height" min="0" max="20" value="3.864734299516908" type="slider" showSettings="false"/>
    <variable name="n2" title="Thickness" min="0" max="20" value="3.671497584541063" type="slider" showSettings="false"/>
    <variable name="n3" type="slider" min="0" max="20" value="12.367149758454106" showSettings="false"/>
    <variable name="aa" type="slider" min="0" max="2" value="0.9565217391304348" showSettings="false"/>
    <variable name="bb" type="slider" min="0" max="2" value="0.9855072463768116" showSettings="false"/>
    <variable name="sides" type="slider" min="0" max="100" value="51.690821256038646"/>
  </variables>
  <layers>
    <path id="path_0" stroke="#DDDDDD" stroke-width="1" stroke-opacity="1" fill="#888888" fill-opacity="0.5" visibility="visible" d="" mb_x="0" mb_y="0" mb_d="supershape m n1 n2 n3 aa bb sides" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="true" mb__showTransform="true">
      <transforms>
        <transform type="rotate" x="0" y="0" angle="50" cx="0" cy="0" sx="1" sy="1"/>
      </transforms>
    </path>
  </layers>
</parametricbox>