<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Magic Box Design</title>
    <id>magicbox.empty</id>
    <author/>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
  </info>
  <variables>
    <variable name="width" title="Width" min="-100" max="100" value="20.40816326530613" type="slider" showSettings="true"/>
    <variable name="height" title="Height" min="-80" max="80" value="-40" type="slider" showSettings="true"/>
  </variables>
  <layers>
    <path id="path_0" stroke="#DDDDDD" stroke-width="1" stroke-opacity="1" fill="#888888" fill-opacity="0.5" visibility="visible" d="" mb_x="0" mb_y="0" mb_d="q width,height 40 0 &#xA;t 40 0 &#xA;t 40 0&#xA;t 40 0&#xA;&#xA;q -height width 0 40&#xA;t 0 40&#xA;t 0 40&#xA;t 0 40&#xA;&#xA;q -width -height -40 0&#xA;t -40 0&#xA;t -40 0&#xA;t -40 0&#xA;&#xA;q height -width 0 -40&#xA;t 0 -40&#xA;t 0 -40&#xA;t 0 -40&#xA;" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="false" mb__showTransform="false">
      <transforms/>
    </path>
  </layers>
</parametricbox>