<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Magic Box Design</title>
    <id>magicbox.empty</id>
    <author/>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
  </info>
  <variables>
    <variable name="widt" type="slider" min="0" max="100" value="10"/>
    <variable name="height" type="slider" min="0" max="100" value="10"/>
    <variable name="depth" type="slider" min="0" max="100" value="10"/>
    <variable name="thickness" type="slider" min="0" max="100" value="10"/>
  </variables>
  <layers>
    <path id="defaultLayer" stroke="#DDDDDD" stroke-width="1" stroke-opacity="1" fill="#888888" fill-opacity="0.5" visibility="visible" d="" mb_x="0" mb_y="0" mb_d="h width&#xD;l thickness thickness&#xD;v height&#xD;l -thickness thickness&#xD;h -width&#xD;l -thickness -thickness&#xD;v -height&#xD;l thickness -thickness" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="false" mb__showTransform="false">
      <transforms/>
    </path>
  </layers>
</parametricbox>