<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Magic Box Design</title>
    <id>magicbox.empty</id>
    <author/>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
  </info>
  <variables>
    <variable id="null" name="width" type="slider" value="13.26530612244898" min="10" max="30" title="null" showSettings="true" description="null"/>
    <variable id="null" name="height" type="slider" value="10.612244897959183" min="10" max="30" title="null" showSettings="true" description="null"/>
  </variables>
  <layers>
    <boolean id="defaultBoolean" mb_x="0" mb_y="0" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="true" mb__showTransform="false" mb__booleanType="union">
      <path id="defaultPath" mb_x="0" mb_y="0" mb_d="circle width&#xA;&#xA;repeat 10 [&#xA;rect 50 50&#xA;m width height&#xA;]" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="false" mb__showTransform="false" mb__staticData="false"/>
    </boolean>
  </layers>
</parametricbox>