<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title>Magic Box Design</title>
    <id>magicbox.empty</id>
    <author/>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
  </info>
  <variables>
    <variable name="width" type="slider" min="0" max="100" value="17.346938775510203"/>
    <variable name="height" type="slider" min="0" max="100" value="42.857142857142854"/>
  </variables>
  <layers>
    <path id="path_0" stroke="#DDDDDD" stroke-width="1" stroke-opacity="1" fill="#888888" fill-opacity="0.5" visibility="visible" d="" mb_x="0" mb_y="0" mb_d="# draw the first rectangle (high)&#xA;rect 10 40&#xA;# draw a small rectangle from the center&#xA;rect 8 16 CENTER&#xA;# move to the right&#xA;move 20 0&#xA;# draw the second rectangle (square)&#xA;rect 30 30&#xA;move 40 0&#xA;# draw the third rectangle (long)&#xA;rect width height&#xA;" mb_stroke="#000000" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="false" mb__showTransform="false">
      <transforms/>
    </path>
  </layers>
</parametricbox>