<?xml version="1.0" encoding="utf-8"?>
<parametricbox version="2.0">
  <info>
    <title></title>
    <id>magicbox.empty</id>
    <author/>
    <website>http://magic-box.org/</website>
    <tutorial/>
    <description>A default design</description>
    <generator xmlns="com.ludens.PackageHandler.view:DesignInfoWindow">v0.9.41</generator>
  </info>
  <variables>
    <variable name="width" type="slider" value="100" min="10" max="700" title="null" showSettings="false" description="null"/>
    <variable name="height" type="slider" value="100" min="10" max="700" title="null" showSettings="false" description="null"/>
  </variables>
  <layers>
    <path id="defaultPath" mb_x="0" mb_y="0" mb_d="h width v height h -width v -height" mb_stroke="#DDDDDD" mb_strokeWidth="1" mb_strokeOpacity="1" mb_fill="#888888" mb_fillOpacity="0.5" mb_visibility="visible" mb__showStroke="true" mb__showFill="false" mb__showTransform="true" mb__staticData="false">
      <transforms>
        <transform type="translate" angle="0" x="10" y="10" cx="0" cy="0" sx="1" sy="1"/>
      </transforms>
    </path>
  </layers>
</parametricbox>